# Generated by Django 2.1.7 on 2019-03-23 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AcLogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Officer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('image', models.ImageField(upload_to='Officer/')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='add_officer',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcAdmin.Department'),
        ),
        migrations.AddField(
            model_name='add_officer',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcLogin.Login'),
        ),
    ]
