# Generated by Django 2.1.7 on 2019-03-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcAdmin', '0003_auto_20190328_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_officer',
            name='department',
            field=models.CharField(max_length=50),
        ),
    ]
