# Generated by Django 2.1.7 on 2019-03-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcAdmin', '0004_auto_20190328_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_officer',
            name='password',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='add_officer',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
