# Generated by Django 2.1.7 on 2019-03-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdetails',
            name='otp',
            field=models.CharField(max_length=6),
        ),
    ]
