# Generated by Django 2.1.7 on 2019-03-23 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AcLogin', '0001_initial'),
        ('AcAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen_Register',
            fields=[
                ('Citizen_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('Address', models.TextField()),
                ('City', models.TextField()),
                ('image', models.ImageField(upload_to='Citizen/')),
                ('status', models.CharField(max_length=20)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcLogin.Login')),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('Complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('image', models.ImageField(upload_to='Complaints/')),
                ('Complaint_registerDate', models.DateField()),
                ('Status', models.CharField(max_length=20)),
                ('Complaint_CLosingDate', models.DateField()),
                ('Citizen_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcCitizen.Citizen_Register')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcAdmin.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('image', models.ImageField(upload_to='Feedback_Images/')),
                ('ComplaintId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcCitizen.Complaints')),
                ('citizen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcCitizen.Citizen_Register')),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('Contact', models.IntegerField(primary_key=True, serialize=False)),
                ('OTP', models.CharField(max_length=6)),
            ],
        ),
    ]
